### ISSUE TITLE
Removes valid imports

### ISSUE THREAD

**Issue by selvarajchennappan** [ajoberstar/gradle-imports#2]
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
It removes import org.slf4j.LoggerFactory; 
and remove java.io.IOException

**Comment by ajoberstar** [comment]
Could you provide a full Java or Groovy file that reproduces this issue?

**Comment by oljeger** [comment]
The `java.io.File` import in the following example is removed by the plugin, although needed:

```
package com.example.myapplication;

import java.io.File;

public interface FileLister {

    File[] listFiles();

}
```

**Comment by oljeger** [comment]
Here's another example: The `java.lang.reflect.Method` import is being removed.
Could this be a Java8 / lambda expression issue?

```
package com.example.myapplication;

import org.reflections.Configuration;
import org.reflections.Reflections;

import java.lang.reflect.Method;
import java.util.stream.Collectors;

public class MyReflections {

    private void doIt() {
        Reflections reflections = new Reflections((Configuration) null);
        reflections.getMethodsReturn(Object.class)
                .stream()
                .map(Method::getDeclaringClass)
                .collect(Collectors.toList());
    }

}
```

**Comment by ajoberstar** [comment]
Yeah, I think the first one the array syntax and the second the method reference. I'm really not using a very smart approach to looking for the usages. It should probably use real Java/Groovy parsers to identify it for real.

**Comment by brunoessmann** [comment]
Thanks for merging. As far as I can see this issue is fixed.

Could you please make a new release so that we can take advantage of the fixes? Thanks a lot!

**Comment by ajoberstar** [comment]
Releases as 1.0.3
